In [2]:
import pandas as pd
import numpy as np
def serialize_df(df):
    # Convert NumPy arrays with nan to lists
    for column in df.columns:
        if df[column].dtype == object and df[column].apply(type).eq(np.ndarray).any():
            df[column] = df[column].apply(lambda arr: arr.tolist() if isinstance(arr, np.ndarray) else arr)

    # Convert DataFrame to JSON string
    json_str = df.to_json(orient='split')
    return json_str

def deserialize_df(json_str):
    # Convert JSON string back to DataFrame
    df = pd.read_json(json_str, orient='split')

    # Convert lists back to NumPy arrays
    for column in df.columns:
        df[column] = df[column].apply(np.array)

    return df

In [3]:
import pandas as pd
import sqlalchemy
import re
import numpy as np
import subprocess
import time
import psycopg2 as ps
def initial_fetch_data():

    engine=sqlalchemy.create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/alpaca") # db instead of localhost for docker
    with engine.begin() as conn:
        query = sqlalchemy.text("""SELECT * FROM alpaca
                            """)
        df = pd.read_sql_query(query, conn)

    df.set_index('Run_Number Run_Number __value', inplace=True)

    # need to convert arrays saved as bytes back to arrays
    byte_columns = [column[:-6] for column in df.columns if column.endswith("_shape") is True and df[column].dtype == object]
    shape_columns = [f'{column}_shape' for column in byte_columns]
    one_dimensional_columns=[]
    two_dimensional_columns=[]

    for shape_column in shape_columns:
        column_name = shape_column[:-6]  # Extract the original column name
        df[shape_column] = df[shape_column].apply(lambda x: tuple(map(int, re.findall(r'\d+', x))) if pd.notnull(x) else None)  # Extract the shape values
        shape_column_values = df[shape_column].dropna()[df[shape_column].dropna() != ()]
        if not shape_column_values.empty:
            length = len(shape_column_values.iloc[0])
        else:
            length = 0
        if length == 1:
            one_dimensional_columns.append(column_name)
        elif length ==2:
            two_dimensional_columns.append(column_name)

    for column in byte_columns:
        shape_column = f'{column}_shape'
        df[column] = df.apply(lambda row: np.frombuffer(row[column]).reshape(row[shape_column]) if pd.notnull(row[column]) and pd.notnull(row[shape_column]) else None, axis=1)

    numerical_columns = df.select_dtypes(include='number').columns

    column_dic={'numerical_columns':numerical_columns,
            'one_dimensional_columns': one_dimensional_columns,
            'two_dimensional_columns': two_dimensional_columns}
    
    runs=df.index.values

    return runs, column_dic


def fetch_run(run_number):
    engine=sqlalchemy.create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/alpaca") # db instead of localhost for docker
    with engine.begin() as conn:
        if run_number:
            query = sqlalchemy.text("""SELECT * FROM alpaca
                            WHERE "Run_Number Run_Number __value" = :run_number
                            """)
            df = pd.read_sql_query(query, conn, params={'run_number': run_number})

    df.set_index('Run_Number Run_Number __value', inplace=True)

    # need to convert arrays saved as bytes back to arrays
    byte_columns = [column[:-6] for column in df.columns if column.endswith("_shape") is True and df[column].dtype == object]
    shape_columns = [f'{column}_shape' for column in byte_columns]

    for shape_column in shape_columns:
        df[shape_column] = df[shape_column].apply(lambda x: tuple(map(int, re.findall(r'\d+', x))) if pd.notnull(x) else None)  # Extract the shape values

    for column in byte_columns:
        shape_column = f'{column}_shape'
        df[column] = df.apply(lambda row: np.frombuffer(row[column]).reshape(row[shape_column]) if pd.notnull(row[column]) and pd.notnull(row[shape_column]) else None, axis=1)
    return df

In [4]:
runs, column_dic =initial_fetch_data()

In [5]:
column_dic

{'numerical_columns': Index(['1TCMOS acq_0 background_corrected roi signal_sum_in_roi',
        'ELENA_Parameters H_offset_mm', 'ELENA_Parameters V_offset_mm',
        'ELENA_Parameters H_angle_mrad', 'ELENA_Parameters V_angle_mrad',
        'Beam_Intensity value', 'Batman acq_0 NestedTrap_OpeningPulseDuration',
        'Batman acq_0 Pbar_CoolingTime', 'Batman acq_0 NegHV_Ch1',
        'Batman acq_0 NegHV_Ch2', 'Batman acq_0 Catch_HotStorageTime',
        'Batman acq_0 NestedTrap_IonStorageTime',
        'Batman acq_0 NestedTrap_TrapFloor',
        'Batman acq_0 NestedTrap_SqueezeTime',
        'Batman acq_0 NestedTrap_SqueezedTrapType',
        'Batman acq_0 NestedTrap_MRTOF_Time',
        'Batman acq_0 NestedTrap_IonCoolingTime',
        'Batman acq_0 NestedTrap_SqueezeRaise', 'Batman acq_0 Pbar_EvapTrim',
        'Batman acq_0 BarrierHeight', 'Batman acq_0 MCP1T_In',
        'SC56 pbars_in_boiloff'],
       dtype='object'),
 'one_dimensional_columns': ['SC56_coinc event_clock',
  'c

In [6]:
run_options = [{'label': number, 'value': number} for number in runs]
run_options

[{'label': 392101, 'value': 392101},
 {'label': 396733, 'value': 396733},
 {'label': 396734, 'value': 396734},
 {'label': 387116, 'value': 387116},
 {'label': 387117, 'value': 387117},
 {'label': 378934, 'value': 378934},
 {'label': 378935, 'value': 378935},
 {'label': 378936, 'value': 378936},
 {'label': 378937, 'value': 378937},
 {'label': 378938, 'value': 378938},
 {'label': 378939, 'value': 378939},
 {'label': 373007, 'value': 373007},
 {'label': 387121, 'value': 387121},
 {'label': 387124, 'value': 387124},
 {'label': 387125, 'value': 387125},
 {'label': 387126, 'value': 387126},
 {'label': 396718, 'value': 396718},
 {'label': 396719, 'value': 396719},
 {'label': 396720, 'value': 396720},
 {'label': 396721, 'value': 396721},
 {'label': 396722, 'value': 396722},
 {'label': 396723, 'value': 396723},
 {'label': 396724, 'value': 396724},
 {'label': 396725, 'value': 396725},
 {'label': 396726, 'value': 396726},
 {'label': 396727, 'value': 396727},
 {'label': 396728, 'value': 396728},
 

In [7]:
df = fetch_run(387121)
df

SC56_coinc event_clock  \
Run_Number Run_Number __value                          
387121                                          None   

                              SC56_coinc event_clock_shape  \
Run_Number Run_Number __value                                
387121                                                None   

                              5TCCD acq_2 background_corrected img_with_roi  \
Run_Number Run_Number __value                                                 
387121                                                                 None   

                              5TCCD acq_2 background_corrected img_with_roi_shape  \
Run_Number Run_Number __value                                                       
387121                                                                      None    

                              1TCMOS acq_0 background_corrected roi signal_sum_in_roi  \
Run_Number Run_Number __value                                                           
387121                                                                      None        

                              ELENA_Parameters H_offset_mm  \
Run_Number Run_Number __value                                
387121                                                None   

                              ELENA_Parameters V_offset_mm  \
Run_Number Run_Number __value                                
387121                                                None   

                              ELENA_Parameters H_angle_mrad  \
Run_Number Run_Number __value                                 
387121                                                 None   

                              ELENA_Parameters V_angle_mrad  \
Run_Number Run_Number __value                                 
387121                                                 None   

                                       captorius3 acq_0 Channel_2_SSPALS Y_[V] t  \
Run_Number Run_Number __value                                                      
387121                         [0.0, 4.000000053405728e-10, 8.000000106811456...   

                               ...  \
Run_Number Run_Number __value  ...   
387121                         ...   

                              1TCMOSacq_1 background_corrected background_normalised_img_shap  \
Run_Number Run_Number __value                                                                   
387121                                                                      None                

                              1TMCP acq_0 V_rebased  \
Run_Number Run_Number __value                         
387121                                         None   

                              1TMCP acq_0 V_rebased_shape 1TMCP acq_0 t  \
Run_Number Run_Number __value                                             
387121                                               None          None   

                              1TMCP acq_0 t_shape SC56 pbars_in_boiloff  \
Run_Number Run_Number __value                                             
387121                                       None                  None   

                              1TCMOS acq_1 background_corrected background_normalised_img  \
Run_Number Run_Number __value                                                               
387121                                                                      None            

                              1TCMOS acq_1 background_corrected background_normalised_img_sha  \
Run_Number Run_Number __value                                                                   
387121                                                                      None                

                              1TCMOS acq_1 bg_corrected bg_normalised_img  \
Run_Number Run_Number __value                                               
387121                                                               None   

                              1TCMOS acq_1 bg_corrected bg_normalised_img_sh

In [8]:
import numpy as np
array_data=np.array([[1,2,3],[3,4,5],[3,7,6]])
another=np.array([0,3,42,23,23])
array_data

array([[1, 2, 3],
       [3, 4, 5],
       [3, 7, 6]])

In [9]:
array_data.dtype, another.dtype, array_data.ndim

(dtype('int32'), dtype('int32'), 2)

In [10]:
array_data=array_data.astype('float64')

In [11]:
array_data

array([[1., 2., 3.],
       [3., 4., 5.],
       [3., 7., 6.]])

In [12]:
from PIL import Image
if array_data.ndim==2:
    original_height, original_width = array_data.shape

                        # Define the target dimensions for the resized image
    target_height = 2
    target_width = int(original_width * (target_height / original_height))

                        # Resize the image using PIL
    resized_image = Image.fromarray(array_data).resize((target_width, target_height))

                        # Convert the resized image back to a NumPy array
    array_data = np.array(resized_image).astype('float64')

byte_data = array_data.tobytes()
array = np.frombuffer(byte_data)
array = array.reshape(array_data.shape)
array_data, array

(array([[1.96428502, 3.3170054 ],
        [4.12464952, 5.95375729]]),
 array([[1.96428502, 3.3170054 ],
        [4.12464952, 5.95375729]]))

In [13]:
array_data.dtype

dtype('float64')

In [14]:
array

array([[1.96428502, 3.3170054 ],
       [4.12464952, 5.95375729]])

In [18]:
engine=sqlalchemy.create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/alpaca")
def fetch_column(column):
    with engine.connect() as conn:  # Use connect() instead of begin() for querying
        if column:
            query = sqlalchemy.text(f"SELECT 'Run_Number Run_Number __value', {column} FROM alpaca")
            df = pd.read_sql_query(query, conn)

    df.set_index('Run_Number Run_Number __value', inplace=True)

    return df


In [19]:
df = fetch_column('ELENA_Parameters H_offset_mm')

KeyError: "None of ['Run_Number Run_Number __value'] are in the columns"